CREATE DATABASE DB011;
USE DB011;
CREATE TABLE OFFICE(NAME VARCHAR(10),ID INT,EMAIL VARCHAR(20),PHONE_NUMBER INT(6));
INSERT INTO OFFICE (NAME,ID,EMAIL,PHONE_NUMBER) VALUES ("AZEYA",1,"AZEYA@123",100),("AMINA",2,"AMINA@123",900),("DEVU",3,"DEVU@123",900);
SET SQL_SAFE_UPDATES=0;
UPDATE OFFICE 
SET NAME="MARIAM"
WHERE ID=2 ;
DELETE FROM OFFICE
WHERE ID=3;
SELECT * FROM OFFICE;



CREATE TABLE STAFF1(NAME VARCHAR(10),S_ID INT,DUTY VARCHAR(7));
INSERT INTO STAFF1(NAME,S_ID,DUTY) VALUES ("ASE",1,890),("DEVU",4,670);
SELECT * FROM STAFF1;
SELECT STAFF1.NAME,S_ID FROM STAFF1
INNER JOIN OFFICE
ON STAFF1.S_ID=OFFICE.ID;

SELECT STAFF1.NAME,S_ID FROM STAFF1
LEFT JOIN OFFICE
ON STAFF1.S_ID=OFFICE.ID;

SELECT STAFF1.NAME,S_ID FROM STAFF1
RIGHT JOIN OFFICE 
ON STAFF1.S_ID=OFFICE.ID;

