CREATE DATABASE BANK_DETAILS;
USE BANK_DETAILS;

CREATE TABLE CUSTOMER_BANK_DETAILS1 (ACC_NO INT PRIMARY KEY,CUST_NAME VARCHAR(25),EMAIL TEXT,PHONE_NUMBER INT,BRANCH_NOMINEE VARCHAR(25),ACC_BALANCE BIGINT);
INSERT INTO CUSTOMER_BANK_DETAILS1(ACC_NO,CUST_NAME,EMAIL,PHONE_NUMBER,BRANCH_NOMINEE,ACC_BALANCE) VALUES(01,"AZE","AZE@GMAIL.COM",123,"MOTHER",10000),(02,"AMINA","AMINA@GMAIL.COM",987,"FATHER",12000),(03,"DEVU","DEVU@GMAIL.COM",766,"MOTHER",1999);
SELECT * FROM CUSTOMER_BANK_DETAILS1;


SET SQL_SAFE_UPDATES=0;
UPDATE CUSTOMER_BANK_DETAILS1
SET ACC_NO=04,CUST_NAME="UTHARA",EMAIL="UTHARA@GMAIL.COM",PHONE_NUMBER=678,BRANCH_NOMINEE="FATHER",ACC_BALANCE=NULL WHERE ACC_NO=03;
SELECT * FROM CUSTOMER_BANK_DETAILS1;

SELECT * FROM CUSTOMER_BANK_DETAILS1 WHERE ACC_BALANCE IS NULL;
SELECT * FROM CUSTOMER_BANK_DETAILS1 WHERE ACC_BALANCE IS NOT NULL; 

SELECT COUNT(ACC_BALANCE),MAX(ACC_BALANCE),MIN(ACC_BALANCE),SUM(ACC_BALANCE),AVG (ACC_BALANCE) FROM CUSTOMER_BANK_DETAILS1;

SELECT CUST_NAME FROM CUSTOMER_BANK_DETAILS1 WHERE CUST_NAME LIKE 'A%';
SELECT CUST_NAME FROM CUSTOMER_BANK_DETAILS1 WHERE CUST_NAME LIKE '__HARA';

SELECT CUST_NAME FROM CUSTOMER_BANK_DETAILS1 WHERE CUST_NAME IN ("AZE");
SELECT ACC_NO,CUST_NAME,EMAIL,PHONE_NUMBER,BRANCH_NOMINEE,ACC_BALANCE FROM CUSTOMER_BANK_DETAILS1 WHERE ACC_NO BETWEEN 1 AND 4;
SELECT* FROM CUSTOMER_BANK_DETAILS1;

SELECT ACC_NO AS ACC FROM CUSTOMER_BANK_DETAILS1;

CREATE TABLE OFFICE_DETAILS(OFF_EMP_ID INT PRIMARY KEY,OFF_EMP_NAME VARCHAR(20),OFF_PHONE_NUM BIGINT);
INSERT INTO OFFICE_DETAILS (OFF_EMP_ID,OFF_EMP_NAME,OFF_PHONE_NUM) VALUES (100,"MARIAM",123),(101,"MIHRA",987);
SELECT * FROM OFFICE_DETAILS;

SELECT PHONE_NUMBER FROM CUSTOMER_BANK_DETAILS1 INNER JOIN OFFICE_DETAILS ON PHONE_NUMBER=PHONE_NUM


