CREATE DATABASE BANK;
USE BANK;

CREATE TABLE CUSTOMER_BANK1 (ACC_NO INT PRIMARY KEY,CUST_NAME VARCHAR(25),EMAIL TEXT,PHONE_NUMBER INT,BRANCH_NOMINEE VARCHAR(25),ACC_BALANCE BIGINT);
INSERT INTO CUSTOMER_BANK1(ACC_NO,CUST_NAME,EMAIL,PHONE_NUMBER,BRANCH_NOMINEE,ACC_BALANCE) VALUES(01,"AZE","AZE@GMAIL.COM",123,"MOTHER",10000),(02,"AMINA","AMINA@GMAIL.COM",987,"FATHER",12000),(03,"DEVU","DEVU@GMAIL.COM",766,"MOTHER",1999);
SELECT * FROM CUSTOMER_BANK1;

SET SQL_SAFE_UPDATES=0;
UPDATE CUSTOMER_BANK1
SET ACC_NO=04,CUST_NAME="UTHARA",EMAIL="UTHARA@GMAIL.COM",PHONE_NUMBER=678,BRANCH_NOMINEE="FATHER",ACC_BALANCE=NULL WHERE ACC_NO=03;
SELECT * FROM CUSTOMER_BANK1;

SELECT CUST_NAME FROM CUSTOMER_BANK1 WHERE PHONE_NUMBER=678 AND ACC_BALANCE=10000;
SELECT * FROM CUSTOMER_BANK1;

SELECT CUST_NAME FROM CUSTOMER_BANK1 WHERE PHONE_NUMBER=123 OR ACC_BALANCE=10000;
SELECT * FROM CUSTOMER_BANK1;

SELECT CUST_NAME FROM CUSTOMER_BANK1 WHERE NOT CUST_NAME="UTHARA" AND ACC_BALANCE>1000;
SELECT * FROM CUSTOMER_BANK1;
SELECT * FROM CUSTOMER_BANK1 WHERE ACC_BALANCE IS NULL;
SELECT * FROM CUSTOMER_BANK1 WHERE ACC_BALANCE IS NOT NULL; 

SELECT MIN(ACC_BALANCE) FROM CUSTOMER_BANK1;
SELECT MAX(ACC_BALANCE) FROM CUSTOMER_BANK1;

SELECT COUNT(ACC_BALANCE) FROM CUSTOMER_BANK1;
SELECT AVG(ACC_BALANCE) FROM CUSTOMER_BANK1;
SELECT SUM(ACC_BALANCE) FROM CUSTOMER_BANK1;
SELECT DISTINCT ACC_BALANCE FROM CUSTOMER_BANK1;

SELECT CUST_NAME FROM CUSTOMER_BANK1 WHERE CUST_NAME LIKE 'A%';
SELECT CUST_NAME FROM CUSTOMER_BANK1 WHERE CUST_NAME LIKE '__HARA';

SELECT CUST_NAME FROM CUSTOMER_BANK LIMIT 1;
SELECT ACC_BALANCE FROM CUSTOMER_BANK1 ORDER BY CUST_NAME DESC;

DESC CUSTOMER_BANK1;

SELECT CUST_NAME FROM CUSTOMER_BANK1 WHERE CUST_NAME IN ("AZE");
SELECT ACC_NO,CUST_NAME,EMAIL,PHONE_NUMBER,BRANCH_NOMINEE,ACC_BALANCE FROM CUSTOMER_BANK1 WHERE ACC_NO BETWEEN 1 AND 4;
SELECT* FROM CUSTOMER_BANK1;

SELECT ACC_NO AS A FROM CUSTOMER_BANK1;

CREATE TABLE EMPL(EMP_ID INT PRIMARY KEY,EMP_NAME VARCHAR(10),EMPL_NO BIGINT);

INSERT INTO EMPL(EMP_ID,EMP_NAME,EMPL_NO) VALUES (01,"A",1234),(09,"B",456);


SELECT ACC_NO FROM CUSTOMER_BANK1
INNER JOIN EMPL ON CUSTOMER_BANK1.ACC_NO=EMPL.EMP_ID;
SELECT ACC_NO FROM CUSTOMER_BANK1
LEFT JOIN EMPL ON CUSTOMER_BANK1.ACC_NO=EMPL.EMP_ID;
SELECT * FROM CUSTOMER_BANK1
RIGHT JOIN EMPL ON CUSTOMER_BANK1.ACC_NO=EMPL.EMP_ID;
SELECT * FROM EMPL;
SELECT ACC_NO.CUSTOMER_BANK1 FROM CUSTOMER_BANK1 
FULL JOIN EMPL
ON CUSTOMER_BANK1.ACC_NO=EMPL.EMP_ID;
SELECT * FROM CUSTOMER_BANK1;
SELECT ACC_NO FROM CUSTOMER_BANK1
UNION
SELECT EMP_ID
FROM EMPL;

SELECT ACC_BALANCE,SUM(ACC_NO)
FROM CUSTOMER_BANK1
GROUP BY ACC_BALANCE;